model_1 = {'B is a Knight': True, 'B is a Knave': True,'A is a Knight': True, 'A is a Knave': True, 'initial_statement_filter': True}
model_2 = {'B is a Knight': True, 'B is a Knave': True,'A is a Knight': True, 'A is a Knave': False}
model_3 = {'B is a Knight': True, 'B is a Knave': True,'A is a Knight': False, 'A is a Knave': True, 'initial_statement_filter': True}
model_4 = {'B is a Knight': True, 'B is a Knave': True,'A is a Knight': False, 'A is a Knave': False}
model_5 = {'B is a Knight': True, 'B is a Knave': False,'A is a Knight': True, 'A is a Knave': True, 'knave_lie_filter': True}
model_6 = {'B is a Knight': True, 'B is a Knave': False,'A is a Knight': True, 'A is a Knave': False, 'initial_knowledge_filter': True} 
model_7 = {'B is a Knight': True, 'B is a Knave': False,'A is a Knight': False, 'A is a Knave': True, 'initial_knowledge_filter': True, 'knave_lie_filter': True}
model_8 = {'B is a Knight': True, 'B is a Knave': False,'A is a Knight': False, 'A is a Knave': False}
model_9 = {'B is a Knight': False, 'B is a Knave': True,'A is a Knight': True, 'A is a Knave': True, 'initial_statement_filter': True}
model_10 = {'B is a Knight': False, 'B is a Knave': True,'A is a Knight': True, 'A is a Knave': False, 'initial_knowledge_filter': True} 
model_11 = {'B is a Knight': False, 'B is a Knave': True, 'A is a Knight': False, 'A is a Knave': True, 'initial_knowledge_filter': True, 'initial_statement_filter': True} 
model_12 = {'B is a Knight': False, 'B is a Knave': True,'A is a Knight': False, 'A is a Knave': False}
model_13 = {'B is a Knight': False, 'B is a Knave': False, 'A is a Knight': True, 'A is a Knave': True, 'knave_lie_filter': True}
model_14 = {'B is a Knight': False, 'B is a Knave': False, 'A is a Knight': True, 'A is a Knave': False}
model_15 = {'B is a Knight': False, 'B is a Knave': False, 'A is a Knight': False, 'A is a Knave': True, 'knave_lie_filter': True}
model_16 = {'B is a Knight': False, 'B is a Knave': False,'A is a Knight': False, 'A is a Knave': False}
